### ISSUE TITLE
What would happen if the CacheStore.store() method throws an exception?

### ISSUE THREAD

**Issue by flyisland** [flyisland/cohPTx#2]

**Comment by flyisland** [comment]
```
Please input 'Account ID':a1
Please input 'balance to change':2
Please input 'Operation(sleep/fail)':storefail
Exception in thread "main" Portable(com.tangosol.util.WrapperException): (Wrapped: Failed request execution for AccountB
alance_D_Srv service on Member(Id=1, Timestamp=2015-09-22 09:43:22.145, Address=10.10.10.1:8088, MachineId=32210, Locati
on=site:,machine:IslandChen-Dell,process:4820, Role=CoherenceServer) (Wrapped: Failed to store key="BalanceId [account_id=a1, balance_id=b6]") LogCacheStore [balances] fail in store(Balance [accountId=a1, balance=12.0, ops=storefail])) LogCacheStore [balances] fail in store(Balance [accountId=a1, balance=12.0, ops=storefail])
        at com.tangosol.util.Base.ensureRuntimeException(Base.java:288)
        at com.tangosol.coherence.component.util.daemon.queueProcessor.service.Grid.tagException(Grid.CDB:36)
        at com.tangosol.coherence.component.util.daemon.queueProcessor.service.grid.partitionedService.PartitionedCache.onInvokeRequest(PartitionedCache.CDB:68)
        at com.tangosol.coherence.component.util.daemon.queueProcessor.service.grid.partitionedService.PartitionedCache$InvokeRequest.run(PartitionedCache.CDB:1)
        at com.tangosol.coherence.component.util.DaemonPool$WrapperTask.run(DaemonPool.CDB:1)
        at com.tangosol.coherence.component.util.DaemonPool$WrapperTask.run(DaemonPool.CDB:32)
        at com.tangosol.coherence.component.util.DaemonPool$Daemon.onNotify(DaemonPool.CDB:63)
        at com.tangosol.coherence.component.util.Daemon.run(Daemon.CDB:42)
        at java.lang.Thread.run(Thread.java:745)
        at <process boundary>
        at com.tangosol.io.pof.ThrowablePofSerializer.deserialize(ThrowablePofSerializer.java:57)
        at com.tangosol.io.pof.PofBufferReader.readAsObject(PofBufferReader.java:3316)
        at com.tangosol.io.pof.PofBufferReader.readObject(PofBufferReader.java:2604)
        at com.tangosol.io.pof.ConfigurablePofContext.deserialize(ConfigurablePofContext.java:368)
        at com.tangosol.coherence.component.util.daemon.queueProcessor.Service.readObject(Service.CDB:1)
        at com.tangosol.coherence.component.net.Message.readObject(Message.CDB:1)
        at com.tangosol.coherence.component.net.message.SimpleResponse.read(SimpleResponse.CDB:6)
        at com.tangosol.coherence.component.util.daemon.queueProcessor.service.Grid.deserializeMessage(Grid.CDB:19)
        at com.tangosol.coherence.component.util.daemon.queueProcessor.service.Grid.onNotify(Grid.CDB:31)
```
